-- PROJECT NAME: Retail Sales Data Analysis
-- AUTHOR: Data Analyst Portfolio
-- PURPOSE: Analyzing customer purchasing behavior and sales performance
-- =======================================================

-- 1. Create Tables
CREATE TABLE customers_data (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100),
    age INT,
    gender VARCHAR(10),
    location VARCHAR(50)
);

CREATE TABLE sales_data (
    order_id INT PRIMARY KEY,
    customer_id INT,
    order_date DATE,
    product_category VARCHAR(50),
    quantity_ordered INT,
    price_per_unit DECIMAL(10,2),
    total_amount DECIMAL(10,2)
);

-- 2. Insert Sample Data
INSERT INTO customers_data VALUES
(101, 'Aarav Sharma', 28, 'Male', 'Mumbai'),
(102, 'Priya Patel', 34, 'Female', 'Delhi'),
(103, 'Amit Verma', 45, 'Male', 'Bangalore'),
(104, 'Sneha Reddy', 22, 'Female', 'Hyderabad'),
(105, 'Rohan Das', 31, 'Male', 'Kolkata');

INSERT INTO sales_data VALUES
(1, 101, '2026-01-10', 'Electronics', 1, 15000.00, 15000.00),
(2, 102, '2026-01-12', 'Clothing', 3, 1200.00, 3600.00),
(3, 103, '2026-01-15', 'Home Decor', 2, 2500.00, 5000.00),
(4, 104, '2026-01-18', 'Electronics', 1, 800.00, 800.00),
(5, 105, '2026-01-20', 'Clothing', 5, 1000.00, 5000.00),
(6, 101, '2026-02-02', 'Home Decor', 1, 4000.00, 4000.00),
(7, 103, '2026-02-05', 'Electronics', 2, 12000.00, 24000.00);


-- =======================================================
-- BUSINESS DATA ANALYSIS QUERIES
-- =======================================================

-- Query 1: Total Revenue Generated by Each Product Category
SELECT 
    product_category, 
    SUM(total_amount) AS total_revenue,
    SUM(quantity_ordered) AS total_items_sold
FROM sales_data
GROUP BY product_category
ORDER BY total_revenue DESC;


-- Query 2: High Value Customers (Who spent more than 5000)
SELECT 
    c.customer_name, 
    c.location, 
    SUM(s.total_amount) AS total_spent
FROM customers_data c
JOIN sales_data s ON c.customer_id = s.customer_id
GROUP BY c.customer_name, c.location
HAVING SUM(s.total_amount) > 5000
ORDER BY total_spent DESC;


-- Query 3: Find Sales Distribution by Gender
SELECT 
    c.gender, 
    COUNT(s.order_id) AS total_orders,
    SUM(s.total_amount) AS total_sales
FROM customers_data c
JOIN sales_data s ON c.customer_id = s.customer_id
GROUP BY c.gender;
